collections:
- name: ansible.posix  # Needs firewalld
- name: ansible.windows
  version: '>=1.5.0'  # Needs win_powershell
- name: community.general  # Needs htpasswd
- name: community.windows
- name: microsoft.ad
  version: '>=1.5.0'  # Uses the identity lookup for objects
