collections:
- name: ansible.posix  # Needs firewalld
- name: ansible.windows
  version: '>=2.8.0'  # Uses newly redirected modules win_dns_record
- name: community.general  # Needs htpasswd
- name: community.windows
- name: microsoft.ad
  version: '>=1.5.0'  # Uses the identity lookup for objects
